

server:
  port: 8080





spring:
  thymeleaf:
    prefix: classpath:/static/
  datasource:
    name: druidDataSource
    # url: jdbc:mysql://118.25.128.221:3559/share?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    url: jdbc:mysql://127.0.0.1:3559/share?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: admin
    password: Ke78MXdFFCyjVscA
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml


# debug: true
